spring.application.name=parser

spring.datasource.url=jdbc:sqlite:database.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-provider-class-name=org.sqlite.SQLiteDataSource
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect